import apiClient from './apiClient';

const saleKeyService = {
  getSaleKeySets: async (outletId) => {
    const params = {};
    if (outletId != null && outletId !== '') {
      params.outletId = Number(outletId);
    }
    const response = await apiClient.get('/sale-keys/sets', {
      params: Object.keys(params).length ? params : undefined,
    });
    return response.data;
  },

  getSaleKeySet: async (setId) => {
    const response = await apiClient.get(`/sale-keys/sets/${setId}`);
    return response.data.saleKeySet;
  },

  createSaleKeySet: async (setData) => {
    const response = await apiClient.post('/sale-keys/sets', setData);
    return response.data.saleKeySet;
  },

  updateSaleKeySet: async (setId, setData) => {
    const response = await apiClient.put(`/sale-keys/sets/${setId}`, setData);
    return response.data.saleKeySet;
  },

  deleteSaleKeySet: async (setId) => {
    const response = await apiClient.delete(`/sale-keys/sets/${setId}`);
    return response.data;
  },

  cloneSaleKeySet: async (setId, newName) => {
    const response = await apiClient.post(`/sale-keys/sets/${setId}/clone`, { name: newName });
    return response.data.saleKeySet;
  },

  getActiveSaleKeySet: async (outletId) => {
    const params = {};
    if (outletId != null && outletId !== '') {
      params.outletId = Number(outletId);
    }
    const response = await apiClient.get('/sale-keys/active', {
      params: Object.keys(params).length ? params : undefined,
    });
    return response.data.saleKeySet;
  },

  getDefaultSaleKeySets: () => {
    return [
      {
        id: 'home-keys',
        name: 'Home Keys',
        description: 'Main sale key layout',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'more-functions',
        name: 'More Functions',
        description: 'Additional function keys',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'products',
        name: 'Products',
        description: 'Product category keys',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'soft-drink',
        name: 'Soft Drink',
        description: 'Soft drink product keys',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'split-beers',
        name: 'Split Beers',
        description: 'Split beer product keys',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ];
  },

  getDefaultConfig: (setId) => {
    const defaultConfigs = {
      'home-keys': {
        gridSize: { rows: 6, cols: 6 },
        saleKeys: [
          {
            id: 'nets-b',
            name: 'NETS B',
            action: 'payment',
            paymentMethod: 'nets',
            backgroundColor: '#000000',
            textColor: '#FFFFFF',
            borderColor: '#000000',
            fontSize: 16,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 0, y: 0 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'ice',
            name: 'ICE',
            action: 'add-product',
            productId: 'ice-product',
            backgroundColor: '#87CEEB',
            textColor: '#000000',
            borderColor: '#000000',
            fontSize: 16,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 1, y: 0 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'premix-10pack',
            name: '10 PACK PREMIX',
            action: 'add-product',
            productId: 'premix-10pack',
            backgroundColor: '#FF0000',
            textColor: '#FFFFFF',
            borderColor: '#000000',
            fontSize: 14,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 2, y: 0 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'clearance',
            name: 'CLEARANCE',
            action: 'special',
            backgroundColor: '#FF0000',
            textColor: '#FFFFFF',
            borderColor: '#000000',
            fontSize: 16,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 3, y: 0 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'beer-slabs',
            name: 'Beer... SLABS',
            action: 'add-product',
            productId: 'beer-slabs',
            backgroundColor: '#000000',
            textColor: '#FFFFFF',
            borderColor: '#000000',
            fontSize: 16,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 4, y: 0 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'split-beer-pks',
            name: 'SPLIT BEER PKS',
            action: 'add-product',
            productId: 'split-beer-pks',
            backgroundColor: '#FFD700',
            textColor: '#000000',
            borderColor: '#000000',
            fontSize: 14,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 5, y: 0 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'premix-slabs-stub',
            name: 'PREMIX SLABS STUB',
            action: 'add-product',
            productId: 'premix-slabs-stub',
            backgroundColor: '#0000FF',
            textColor: '#FFFFFF',
            borderColor: '#000000',
            fontSize: 14,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 0, y: 1 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'split-premix-pks',
            name: 'SPLIT PREMIX PKS',
            action: 'add-product',
            productId: 'split-premix-pks',
            backgroundColor: '#FF00FF',
            textColor: '#FFFFFF',
            borderColor: '#000000',
            fontSize: 14,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 1, y: 1 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'premix-slabs-cans',
            name: 'PREMIX SLABS CANS',
            action: 'add-product',
            productId: 'premix-slabs-cans',
            backgroundColor: '#FF0000',
            textColor: '#FFFFFF',
            borderColor: '#000000',
            fontSize: 14,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 2, y: 1 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'cider',
            name: 'CIDER',
            action: 'add-product',
            productId: 'cider',
            backgroundColor: '#FFFFFF',
            textColor: '#000000',
            borderColor: '#000000',
            fontSize: 16,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 3, y: 1 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'soft-drinks',
            name: 'SOFT DRINKS',
            action: 'add-product',
            productId: 'soft-drinks',
            backgroundColor: '#FFD700',
            textColor: '#000000',
            borderColor: '#000000',
            fontSize: 16,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 4, y: 1 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'case-qty',
            name: 'Case Qty',
            action: 'special',
            backgroundColor: '#0000FF',
            textColor: '#FFFFFF',
            borderColor: '#000000',
            fontSize: 16,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 5, y: 1 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'go-to-2nd-page',
            name: 'Go to 2nd page',
            action: 'navigation',
            backgroundColor: '#FFD700',
            textColor: '#000000',
            borderColor: '#000000',
            fontSize: 14,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 0, y: 2 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'party-packs',
            name: 'Party Packs',
            action: 'add-product',
            productId: 'party-packs',
            backgroundColor: '#FFD700',
            textColor: '#000000',
            borderColor: '#000000',
            fontSize: 16,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 1, y: 2 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'legal-age',
            name: 'Legal Age 7th Aug 2007',
            action: 'info',
            backgroundColor: '#FF0000',
            textColor: '#FFFFFF',
            borderColor: '#000000',
            fontSize: 12,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 2, y: 2 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'gift-voucher',
            name: 'PMK GIFT VOUCHER',
            action: 'special',
            backgroundColor: '#FFD700',
            textColor: '#000000',
            borderColor: '#000000',
            fontSize: 14,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 3, y: 2 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'exact-cash',
            name: 'Exact Cash',
            action: 'payment',
            paymentMethod: 'cash',
            backgroundColor: '#00FF00',
            textColor: '#000000',
            borderColor: '#000000',
            fontSize: 16,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 4, y: 2 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'cancel-sale',
            name: 'Cancel Sale',
            action: 'clear-sale',
            backgroundColor: '#FF0000',
            textColor: '#FFFFFF',
            borderColor: '#000000',
            fontSize: 16,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 5, y: 2 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'eftpos',
            name: 'EFTPOS',
            action: 'payment',
            paymentMethod: 'eftpos',
            backgroundColor: '#FF0000',
            textColor: '#FFFFFF',
            borderColor: '#000000',
            fontSize: 16,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 0, y: 3 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'mobile-eftpos',
            name: 'MOBILE EFTPOS',
            action: 'payment',
            paymentMethod: 'mobile-eftpos',
            backgroundColor: '#FFD700',
            textColor: '#000000',
            borderColor: '#000000',
            fontSize: 14,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 1, y: 3 },
            size: { width: 1, height: 1 },
            image: null,
          },
        ],
      },
      'more-functions': {
        gridSize: { rows: 4, cols: 4 },
        saleKeys: [
          {
            id: 'clear-sale',
            name: 'Clear Sale',
            action: 'clear-sale',
            backgroundColor: '#FF0000',
            textColor: '#FFFFFF',
            borderColor: '#000000',
            fontSize: 16,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 0, y: 0 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'minus-quantity',
            name: 'Minus Quantity',
            action: 'subtract-quantity',
            backgroundColor: '#FFA500',
            textColor: '#000000',
            borderColor: '#000000',
            fontSize: 16,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 1, y: 0 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'plus-quantity',
            name: 'Plus Quantity',
            action: 'add-quantity',
            backgroundColor: '#00FF00',
            textColor: '#000000',
            borderColor: '#000000',
            fontSize: 16,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 2, y: 0 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'case-quantity',
            name: 'Case Quantity',
            action: 'case-quantity',
            backgroundColor: '#00FF00',
            textColor: '#000000',
            borderColor: '#000000',
            fontSize: 16,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 3, y: 0 },
            size: { width: 1, height: 1 },
            image: null,
          },
        ],
      },
      'products': {
        gridSize: { rows: 3, cols: 4 },
        saleKeys: [
          {
            id: 'clearance-fridge-6pk',
            name: 'Clearance Fridge (6PK)',
            action: 'add-product',
            productId: 'clearance-fridge-6pk',
            backgroundColor: '#00FF00',
            textColor: '#000000',
            borderColor: '#000000',
            fontSize: 14,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 0, y: 0 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'clearance-fridge-4pk',
            name: 'Clearance Fridge (4PK)',
            action: 'add-product',
            productId: 'clearance-fridge-4pk',
            backgroundColor: '#FF0000',
            textColor: '#FFFFFF',
            borderColor: '#000000',
            fontSize: 14,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 1, y: 0 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'ice-5kg',
            name: 'ICE 5kg',
            action: 'add-product',
            productId: 'ice-5kg',
            backgroundColor: '#87CEEB',
            textColor: '#000000',
            borderColor: '#000000',
            fontSize: 16,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 2, y: 0 },
            size: { width: 1, height: 1 },
            image: null,
          },
          {
            id: 'party-packs',
            name: 'Party Packs',
            action: 'add-product',
            productId: 'party-packs',
            backgroundColor: '#FFD700',
            textColor: '#000000',
            borderColor: '#000000',
            fontSize: 16,
            textStyle: { bold: true, italic: false, underline: false },
            behavior: {
              disableKey: false,
              preventDisable: false,
              preventHover: false,
              preventHoverAnimation: false,
            },
            position: { x: 3, y: 0 },
            size: { width: 1, height: 1 },
            image: null,
          },
        ],
      },
    };

    return defaultConfigs[setId] || {
      gridSize: { rows: 6, cols: 6 },
      saleKeys: [],
    };
  },
};

export default saleKeyService;
